var manualSendResults = true;
var shuffleSequence = seq("intro", sepWith("sep", seq("p", rshuffle("q4"))),"sr","done");
var practiceItemTypes = ["practice"];

var defaults = [
    "Separator", {
        transfer: 1000,
        normalMessage: "Please wait for the next sentence.",
        errorMessage: "Incorrect. Please wait for the next sentence.",
        hideProgressBar: true,
        continueOnReturn: true
    },
    "DashedSentence", {
        mode: "self-paced reading"
    },
    "Question", {
        hasCorrect: true
    },
    "AcceptabilityJudgment", {
        as: ["1", "2", "3", "4", "5", "6", "7"],
        presentAsScale: true,
        leftComment: "(most like an event)", rightComment: "(most like a state of affairs)",
        hideProgressBar: false
    },
    "Message", {
        hideProgressBar: true,
        continueOnReturn: true
    },
    "Form", {
        hideProgressBar: true,
        continueOnReturn: true
    }
];

var items = [
    ["sr", "__SendResults__", { }],
    ["sep", "Separator", { }],

    ["intro", "Form", {
        html: { include: "intro.html" },
        validators: {
            age: function (s) { if (s.match(/^\d+$/)) return true; else return "Bad value for \u2018age\u2019"; }
        }
    } ],
   
    ["intro", "Message", {
        html: { include: "intro2.html" }
    } ],
    ["intro", "Message", {html:["div",["p", "Ready to get started?"]]}],

    ["done", "Exit", {
        html: { include: "done.html" }
    } ],

    ["p", "AcceptabilityJudgment", {s: "Martinez crashed into the wall on the play."}],
    ["p", "AcceptabilityJudgment", {s: "Some bound volumes remained in the library's collection."}],
    ["p", "AcceptabilityJudgment", {s: "He always exuded energy and good cheer."}],
    
    ["q1", "AcceptabilityJudgment", {s: "He invaded."}],
    ["q1", "AcceptabilityJudgment", {s: "He strapped a dynamite bomb on himself."}],
    ["q1", "AcceptabilityJudgment", {s: "I ate right."}],
    ["q1", "AcceptabilityJudgment", {s: "I called."}],
    ["q1", "AcceptabilityJudgment", {s: "I did a lot of walking."}],
    ["q1", "AcceptabilityJudgment", {s: "I just gave them a phone call."}],
    ["q1", "AcceptabilityJudgment", {s: "I picked up the phone."}],
    ["q1", "AcceptabilityJudgment", {s: "I pulled up to the front."}],
    ["q1", "AcceptabilityJudgment", {s: "I shopped."}],
    ["q1", "AcceptabilityJudgment", {s: "I spent time reading about this."}],
    ["q1", "AcceptabilityJudgment", {s: "I spoke to my best friend."}],
    ["q1", "AcceptabilityJudgment", {s: "I stayed off drugs."}],
    ["q1", "AcceptabilityJudgment", {s: "I told the guy if I sneeze my belt buckle was gonna hit him in the head."}],
    ["q1", "AcceptabilityJudgment", {s: "I walked in the bank."}],
    ["q1", "AcceptabilityJudgment", {s: "It probably destroyed him."}],
    ["q1", "AcceptabilityJudgment", {s: "It sent email."}],
    ["q1", "AcceptabilityJudgment", {s: "She spent time on the internet."}],
    ["q1", "AcceptabilityJudgment", {s: "She took off her socks."}],
    ["q1", "AcceptabilityJudgment", {s: "Somebody hijacked a crop duster."}],
    ["q1", "AcceptabilityJudgment", {s: "The player acceped an offer."}],
    ["q1", "AcceptabilityJudgment", {s: "They actually used computers to make the education process better."}],
    ["q1", "AcceptabilityJudgment", {s: "They called my husband."}],
    ["q1", "AcceptabilityJudgment", {s: "They destroyed one of those cooling towers or whatever they have."}],
    ["q1", "AcceptabilityJudgment", {s: "They instilled the right morals in them."}],
    ["q1", "AcceptabilityJudgment", {s: "They played a video game."}],
    ["q1", "AcceptabilityJudgment", {s: "They really made it quiet."}],
    ["q1", "AcceptabilityJudgment", {s: "They said where have you been."}],
    ["q1", "AcceptabilityJudgment", {s: "They sent their people to infiltrate our country like the terrorists did."}],
    ["q1", "AcceptabilityJudgment", {s: "They served you some food."}],
    ["q1", "AcceptabilityJudgment", {s: "We decided what grade level it would be."}],
    ["q1", "AcceptabilityJudgment", {s: "We freed people."}],
    ["q1", "AcceptabilityJudgment", {s: "We got on with the topic."}],
    ["q1", "AcceptabilityJudgment", {s: "We kept those people under surveillance."}],
    ["q1", "AcceptabilityJudgment", {s: "We protected ourselves and the Iraqi people."}],
    ["q1", "AcceptabilityJudgment", {s: "We said we'd be willing to talk to you about anything you want to."}],
    ["q1", "AcceptabilityJudgment", {s: "We said what would happen if somebody said that they would give us a million dollars."}],
    ["q1", "AcceptabilityJudgment", {s: "You ate less."}],
    ["q1", "AcceptabilityJudgment", {s: "You bought a house and a couple of cars."}],
    ["q1", "AcceptabilityJudgment", {s: "You changed the writing part."}],
    ["q1", "AcceptabilityJudgment", {s: "You developed a stable relationship before going into a marriage that's not gonna be happy."}],
    ["q1", "AcceptabilityJudgment", {s: "You enabled them."}],
    ["q1", "AcceptabilityJudgment", {s: "You enjoyed the meal you just ate."}],
    ["q1", "AcceptabilityJudgment", {s: "You followed the prompts."}],
    ["q1", "AcceptabilityJudgment", {s: "You just ignored it."}],
    ["q1", "AcceptabilityJudgment", {s: "You lay down."}],
    ["q1", "AcceptabilityJudgment", {s: "You placed the best government possible in place."}],
    ["q1", "AcceptabilityJudgment", {s: "You really preoccupied yourself with that."}],
    ["q1", "AcceptabilityJudgment", {s: "You saw what she's wearing."}],
    ["q1", "AcceptabilityJudgment", {s: "You spoke it."}],
    ["q1", "AcceptabilityJudgment", {s: "You started over."}],
    ["q1", "AcceptabilityJudgment", {s: "You talked to me."}],
    ["q1", "AcceptabilityJudgment", {s: "You took away not so much the means but maybe the cause."}],
    ["q1", "AcceptabilityJudgment", {s: "You were a parent."}],
    ["q2", "AcceptabilityJudgment", {s: "A voucher took all the kids in an area."}],
    ["q2", "AcceptabilityJudgment", {s: "Everyone talked about it."}],
    ["q2", "AcceptabilityJudgment", {s: "He ate."}],
    ["q2", "AcceptabilityJudgment", {s: "He just showed us where those weapons were."}],
    ["q2", "AcceptabilityJudgment", {s: "He ran on the wheel."}],
    ["q2", "AcceptabilityJudgment", {s: "He saved his dog."}],
    ["q2", "AcceptabilityJudgment", {s: "His brother endorsed him."}],
    ["q2", "AcceptabilityJudgment", {s: "I bought some books."}],
    ["q2", "AcceptabilityJudgment", {s: "I bought three Dove products."}],
    ["q2", "AcceptabilityJudgment", {s: "I created a sole proprietorship."}],
    ["q2", "AcceptabilityJudgment", {s: "I identified."}],
    ["q2", "AcceptabilityJudgment", {s: "I joined Netflix."}],
    ["q2", "AcceptabilityJudgment", {s: "I just stayed in shape."}],
    ["q2", "AcceptabilityJudgment", {s: "I killed."}],
    ["q2", "AcceptabilityJudgment", {s: "I shut down both those businesses a year ago."}],
    ["q2", "AcceptabilityJudgment", {s: "I sold on consignment."}],
    ["q2", "AcceptabilityJudgment", {s: "I supported our President in what he chose to do."}],
    ["q2", "AcceptabilityJudgment", {s: "I traveled."}],
    ["q2", "AcceptabilityJudgment", {s: "I used to reach for a cigarette."}],
    ["q2", "AcceptabilityJudgment", {s: "It led to more conflict."}],
    ["q2", "AcceptabilityJudgment", {s: "It opened their eyes to the rest of the world."}],
    ["q2", "AcceptabilityJudgment", {s: "She found out the schedule."}],
    ["q2", "AcceptabilityJudgment", {s: "That raised the humidity level."}],
    ["q2", "AcceptabilityJudgment", {s: "The states spent all their time and energy trying to get a separate state for Palestine."}],
    ["q2", "AcceptabilityJudgment", {s: "They created a portabl ecomputer."}],
    ["q2", "AcceptabilityJudgment", {s: "They delivered the lecture."}],
    ["q2", "AcceptabilityJudgment", {s: "They disagreed with what we think proper foreign policy is."}],
    ["q2", "AcceptabilityJudgment", {s: "They fought."}],
    ["q2", "AcceptabilityJudgment", {s: "They just fired them all."}],
    ["q2", "AcceptabilityJudgment", {s: "They just paid you for your meal."}],
    ["q2", "AcceptabilityJudgment", {s: "They raised it to seven and a quarter an hour."}],
    ["q2", "AcceptabilityJudgment", {s: "They saved the person who runs the library."}],
    ["q2", "AcceptabilityJudgment", {s: "They stopped at Steak 'n Shake."}],
    ["q2", "AcceptabilityJudgment", {s: "They wanted you to put them on medicines."}],
    ["q2", "AcceptabilityJudgment", {s: "We ate."}],
    ["q2", "AcceptabilityJudgment", {s: "We developed a defense against it."}],
    ["q2", "AcceptabilityJudgment", {s: "We discussed the topic then."}],
    ["q2", "AcceptabilityJudgment", {s: "We let it spend the last few years around other birds."}],
    ["q2", "AcceptabilityJudgment", {s: "We strengthened our immigration."}],
    ["q2", "AcceptabilityJudgment", {s: "We taught them how to talk."}],
    ["q2", "AcceptabilityJudgment", {s: "We thought about ourselves."}],
    ["q2", "AcceptabilityJudgment", {s: "We tried to bring them down."}],
    ["q2", "AcceptabilityJudgment", {s: "We watched the last two episodes."}],
    ["q2", "AcceptabilityJudgment", {s: "You did a little bit of exercise."}],
    ["q2", "AcceptabilityJudgment", {s: "You did what you think is best for yourself"}],
    ["q2", "AcceptabilityJudgment", {s: "You drove half an hour from here."}],
    ["q2", "AcceptabilityJudgment", {s: "You exercised."}],
    ["q2", "AcceptabilityJudgment", {s: "You popped them in."}],
    ["q2", "AcceptabilityJudgment", {s: "You prepared it."}],
    ["q2", "AcceptabilityJudgment", {s: "You talked to people."}],
    ["q2", "AcceptabilityJudgment", {s: "You treated the symptoms."}],
    ["q2", "AcceptabilityJudgment", {s: "You walked the hallways of the middle school."}],
    ["q2", "AcceptabilityJudgment", {s: "You were able to respect what they're feeling."}],
    ["q3", "AcceptabilityJudgment", {s: "Everyone continued to promote the justice."}],
    ["q3", "AcceptabilityJudgment", {s: "Friends got you in trouble."}],
    ["q3", "AcceptabilityJudgment", {s: "I asked her \u201CAre you trained in mouth-to-mouth resuscitation?\u201D"}],
    ["q3", "AcceptabilityJudgment", {s: "I continued my education."}],
    ["q3", "AcceptabilityJudgment", {s: "I drove my car."}],
    ["q3", "AcceptabilityJudgment", {s: "I facilitated you figuring it out."}],
    ["q3", "AcceptabilityJudgment", {s: "I finished college."}],
    ["q3", "AcceptabilityJudgment", {s: "I opened my mouth and they knew exactly where I'm from."}],
    ["q3", "AcceptabilityJudgment", {s: "I packed a picnic lunch."}],
    ["q3", "AcceptabilityJudgment", {s: "I picked up my car keys."}],
    ["q3", "AcceptabilityJudgment", {s: "I was different with my money."}],
    ["q3", "AcceptabilityJudgment", {s: "I was up in a plane."}],
    ["q3", "AcceptabilityJudgment", {s: "I went downstairs."}],
    ["q3", "AcceptabilityJudgment", {s: "It really gave you liquid."}],
    ["q3", "AcceptabilityJudgment", {s: "It shortened your life."}],
    ["q3", "AcceptabilityJudgment", {s: "My aunt went from Buffalo to Toronto."}],
    ["q3", "AcceptabilityJudgment", {s: "My husband's parents held him."}],
    ["q3", "AcceptabilityJudgment", {s: "People automatically panicked."}],
    ["q3", "AcceptabilityJudgment", {s: "People invested a nickel in them."}],
    ["q3", "AcceptabilityJudgment", {s: "People thought about what was really important in life."}],
    ["q3", "AcceptabilityJudgment", {s: "That person kept everyone calm."}],
    ["q3", "AcceptabilityJudgment", {s: "They brought jobs to the community."}],
    ["q3", "AcceptabilityJudgment", {s: "They changed their name."}],
    ["q3", "AcceptabilityJudgment", {s: "They fought."}],
    ["q3", "AcceptabilityJudgment", {s: "They gave me minimum."}],
    ["q3", "AcceptabilityJudgment", {s: "They made the theme suggestion."}],
    ["q3", "AcceptabilityJudgment", {s: "They restricted those chemicals."}],
    ["q3", "AcceptabilityJudgment", {s: "They staged a work slowdown."}],
    ["q3", "AcceptabilityJudgment", {s: "They watched cable television."}],
    ["q3", "AcceptabilityJudgment", {s: "They worked with the companies."}],
    ["q3", "AcceptabilityJudgment", {s: "We educated young people not to start."}],
    ["q3", "AcceptabilityJudgment", {s: "We gathered up all of the kids and their parents."}],
    ["q3", "AcceptabilityJudgment", {s: "We just pulled out."}],
    ["q3", "AcceptabilityJudgment", {s: "We talked about the holidays and stuff."}],
    ["q3", "AcceptabilityJudgment", {s: "We talked about the topics for ten minutes."}],
    ["q3", "AcceptabilityJudgment", {s: "We wrote little programs to make your name blink on the screen or something like that."}],
    ["q3", "AcceptabilityJudgment", {s: "You abolished religion."}],
    ["q3", "AcceptabilityJudgment", {s: "You accepted the million dollars."}],
    ["q3", "AcceptabilityJudgment", {s: "You added four flowers to water and sugar and you have a flowered tea."}],
    ["q3", "AcceptabilityJudgment", {s: "You added stuff to the dirt."}],
    ["q3", "AcceptabilityJudgment", {s: "You called him."}],
    ["q3", "AcceptabilityJudgment", {s: "You condoned that."}],
    ["q3", "AcceptabilityJudgment", {s: "You educated yourself."}],
    ["q3", "AcceptabilityJudgment", {s: "You found out the lottery numbers."}],
    ["q3", "AcceptabilityJudgment", {s: "You found somebody that you know."}],
    ["q3", "AcceptabilityJudgment", {s: "You had your main meal in the middle."}],
    ["q3", "AcceptabilityJudgment", {s: "You jumped right back off."}],
    ["q3", "AcceptabilityJudgment", {s: "You lived off the interest."}],
    ["q3", "AcceptabilityJudgment", {s: "You relaxed."}],
    ["q3", "AcceptabilityJudgment", {s: "You thought when you were watching TV."}],
    ["q3", "AcceptabilityJudgment", {s: "You traumatized another generation."}],
    ["q3", "AcceptabilityJudgment", {s: "You went back to graduate school at that point."}],
    ["q3", "AcceptabilityJudgment", {s: "You were inside."}],
    ["q4", "AcceptabilityJudgment", {s: "He called me."}],
    ["q4", "AcceptabilityJudgment", {s: "He kept touching himself."}],
    ["q4", "AcceptabilityJudgment", {s: "He played his X-box."}],
    ["q4", "AcceptabilityJudgment", {s: "He was a waiter."}],
    ["q4", "AcceptabilityJudgment", {s: "He was reasonably attractive."}],
    ["q4", "AcceptabilityJudgment", {s: "I bought a nice car."}],
    ["q4", "AcceptabilityJudgment", {s: "I had a toy store."}],
    ["q4", "AcceptabilityJudgment", {s: "I hung out with my friends=."}],
    ["q4", "AcceptabilityJudgment", {s: "I joined."}],
    ["q4", "AcceptabilityJudgment", {s: "I paid the bills"}],
    ["q4", "AcceptabilityJudgment", {s: "I put myself in that situation."}],
    ["q4", "AcceptabilityJudgment", {s: "I saw you guys graduate from college."}],
    ["q4", "AcceptabilityJudgment", {s: "I sent them to click on their television."}],
    ["q4", "AcceptabilityJudgment", {s: "I stood on the porch."}],
    ["q4", "AcceptabilityJudgment", {s: "I took the over-the-counter medicine."}],
    ["q4", "AcceptabilityJudgment", {s: "I was on a game show."}],
    ["q4", "AcceptabilityJudgment", {s: "It caused more problems and more conflict."}],
    ["q4", "AcceptabilityJudgment", {s: "It collected newspapers from around the world."}],
    ["q4", "AcceptabilityJudgment", {s: "It raised that eyebrow."}],
    ["q4", "AcceptabilityJudgment", {s: "She bought stuff for her family."}],
    ["q4", "AcceptabilityJudgment", {s: "She showed up."}],
    ["q4", "AcceptabilityJudgment", {s: "The government gave tax breaks for switching."}],
    ["q4", "AcceptabilityJudgment", {s: "They asked questions about the mole."}],
    ["q4", "AcceptabilityJudgment", {s: "They built a bigger stadium with more private boxes."}],
    ["q4", "AcceptabilityJudgment", {s: "They flew a plane into something."}],
    ["q4", "AcceptabilityJudgment", {s: "They just stuck it in there."}],
    ["q4", "AcceptabilityJudgment", {s: "They killed Americans."}],
    ["q4", "AcceptabilityJudgment", {s: "They laughed."}],
    ["q4", "AcceptabilityJudgment", {s: "They prescribed you a drug that you could get over the counter."}],
    ["q4", "AcceptabilityJudgment", {s: "This President was able to tell you."}],
    ["q4", "AcceptabilityJudgment", {s: "We argued."}],
    ["q4", "AcceptabilityJudgment", {s: "We discussed our topic for ten minutes."}],
    ["q4", "AcceptabilityJudgment", {s: "We let them."}],
    ["q4", "AcceptabilityJudgment", {s: "We scanned the people as they come through."}],
    ["q4", "AcceptabilityJudgment", {s: "We stripped some veins out of your left leg and put them in your right leg."}],
    ["q4", "AcceptabilityJudgment", {s: "We supported him fully right through his worst atrocities."}],
    ["q4", "AcceptabilityJudgment", {s: "We supported their countries."}],
    ["q4", "AcceptabilityJudgment", {s: "We were very sceptical about it."}],
    ["q4", "AcceptabilityJudgment", {s: "You created environment."}],
    ["q4", "AcceptabilityJudgment", {s: "You got your password."}],
    ["q4", "AcceptabilityJudgment", {s: "You just left yourself sensitive to God."}],
    ["q4", "AcceptabilityJudgment", {s: "You just threw it in there."}],
    ["q4", "AcceptabilityJudgment", {s: "You looked like you belong in the clubhouse."}],
    ["q4", "AcceptabilityJudgment", {s: "You paid your money for a guy who can get himself on base."}],
    ["q4", "AcceptabilityJudgment", {s: "You picked on someone like this right in front of an audience."}],
    ["q4", "AcceptabilityJudgment", {s: "You pulled the fire alarm."}],
    ["q4", "AcceptabilityJudgment", {s: "You sat there."}],
    ["q4", "AcceptabilityJudgment", {s: "You stayed inside."}],
    ["q4", "AcceptabilityJudgment", {s: "You stopped by Maxwell Street."}],
    ["q4", "AcceptabilityJudgment", {s: "You treated the symptoms."}],
    ["q4", "AcceptabilityJudgment", {s: "You were an individual."}],
    ["q4", "AcceptabilityJudgment", {s: "You were defensive."}],
    ["q4", "AcceptabilityJudgment", {s: "You worked there."}],
    ["q5", "AcceptabilityJudgment", {s: "He earned that first million."}],
    ["q5", "AcceptabilityJudgment", {s: "He turned around."}],
    ["q5", "AcceptabilityJudgment", {s: "I actually had an establishment."}],
    ["q5", "AcceptabilityJudgment", {s: "I danced the whole time."}],
    ["q5", "AcceptabilityJudgment", {s: "I ran out the door."}],
    ["q5", "AcceptabilityJudgment", {s: "I rode a bike."}],
    ["q5", "AcceptabilityJudgment", {s: "I substitute taught."}],
    ["q5", "AcceptabilityJudgment", {s: "I survived."}],
    ["q5", "AcceptabilityJudgment", {s: "I was outside hanging out with people."}],
    ["q5", "AcceptabilityJudgment", {s: "I was the assistant junior high youth pastor."}],
    ["q5", "AcceptabilityJudgment", {s: "It confirmed my suspicions."}],
    ["q5", "AcceptabilityJudgment", {s: "It promoted this celebrity's getting married."}],
    ["q5", "AcceptabilityJudgment", {s: "Our country stepped in."}],
    ["q5", "AcceptabilityJudgment", {s: "Our government and the people were alert."}],
    ["q5", "AcceptabilityJudgment", {s: "Steinbrenner won."}],
    ["q5", "AcceptabilityJudgment", {s: "That pushed the stock down worse."}],
    ["q5", "AcceptabilityJudgment", {s: "They avoided dead air time."}],
    ["q5", "AcceptabilityJudgment", {s: "They changed the graphics."}],
    ["q5", "AcceptabilityJudgment", {s: "They just sat around all day."}],
    ["q5", "AcceptabilityJudgment", {s: "They just showed up."}],
    ["q5", "AcceptabilityJudgment", {s: "They left an anonymous tip."}],
    ["q5", "AcceptabilityJudgment", {s: "They looked at the suburban schools."}],
    ["q5", "AcceptabilityJudgment", {s: "They minded their own business."}],
    ["q5", "AcceptabilityJudgment", {s: "They passed through the gates."}],
    ["q5", "AcceptabilityJudgment", {s: "They picked out a demographic area."}],
    ["q5", "AcceptabilityJudgment", {s: "They sat on the computer all day."}],
    ["q5", "AcceptabilityJudgment", {s: "They sent somebody over to our country."}],
    ["q5", "AcceptabilityJudgment", {s: "They showed their face."}],
    ["q5", "AcceptabilityJudgment", {s: "They sold."}],
    ["q5", "AcceptabilityJudgment", {s: "They started building stadiums."}],
    ["q5", "AcceptabilityJudgment", {s: "They stopped them from scoring once."}],
    ["q5", "AcceptabilityJudgment", {s: "They tried to set up a democratic government that is secular."}],
    ["q5", "AcceptabilityJudgment", {s: "They wanted to feed you."}],
    ["q5", "AcceptabilityJudgment", {s: "We just kept our eyes open."}],
    ["q5", "AcceptabilityJudgment", {s: "We learned."}],
    ["q5", "AcceptabilityJudgment", {s: "We painted it."}],
    ["q5", "AcceptabilityJudgment", {s: "We rebuilt the intelligence community so that they're getting straight information."}],
    ["q5", "AcceptabilityJudgment", {s: "We turned the whole population against us."}],
    ["q5", "AcceptabilityJudgment", {s: "We watched."}],
    ["q5", "AcceptabilityJudgment", {s: "You accepted their emails."}],
    ["q5", "AcceptabilityJudgment", {s: "You brought a child into this world."}],
    ["q5", "AcceptabilityJudgment", {s: "You did things."}],
    ["q5", "AcceptabilityJudgment", {s: "You established this."}],
    ["q5", "AcceptabilityJudgment", {s: "You just backed out."}],
    ["q5", "AcceptabilityJudgment", {s: "You just let the children learn at whatever rate that they were comfortable with. "}],
    ["q5", "AcceptabilityJudgment", {s: "You maintained a litter box."}],
    ["q5", "AcceptabilityJudgment", {s: "You played the machines with your club card."}],
    ["q5", "AcceptabilityJudgment", {s: "You said the date and people automatically knew what you were talking about."}],
    ["q5", "AcceptabilityJudgment", {s: "You stood there."}],
    ["q5", "AcceptabilityJudgment", {s: "You were alive."}],
    ["q5", "AcceptabilityJudgment", {s: "You were in the same room with someone coughing."}],
    ["q5", "AcceptabilityJudgment", {s: "You will go look for a card."}],
    ["q5", "AcceptabilityJudgment", {s: "You'd slipped a twenty to the right person."}],
    ["q6", "AcceptabilityJudgment", {s: "He fired a couple of people."}],
    ["q6", "AcceptabilityJudgment", {s: "He got over the booze."}],
    ["q6", "AcceptabilityJudgment", {s: "He hung out with the people from work."}],
    ["q6", "AcceptabilityJudgment", {s: "He spent the money."}],
    ["q6", "AcceptabilityJudgment", {s: "I did a lot of writing."}],
    ["q6", "AcceptabilityJudgment", {s: "I had my daughter move into the house with me."}],
    ["q6", "AcceptabilityJudgment", {s: "I invested my time in something past."}],
    ["q6", "AcceptabilityJudgment", {s: "I laid down my main vocals."}],
    ["q6", "AcceptabilityJudgment", {s: "I picked up the phone."}],
    ["q6", "AcceptabilityJudgment", {s: "I punched it into a search engine."}],
    ["q6", "AcceptabilityJudgment", {s: "I spent."}],
    ["q6", "AcceptabilityJudgment", {s: "I turned it on."}],
    ["q6", "AcceptabilityJudgment", {s: "I walked stairs."}],
    ["q6", "AcceptabilityJudgment", {s: "It turned everybody off to all reality TV."}],
    ["q6", "AcceptabilityJudgment", {s: "She showed me."}],
    ["q6", "AcceptabilityJudgment", {s: "She was cremated."}],
    ["q6", "AcceptabilityJudgment", {s: "Somebody shipped it in the cargo."}],
    ["q6", "AcceptabilityJudgment", {s: "That made sure that you are going to be supportive of each other."}],
    ["q6", "AcceptabilityJudgment", {s: "The terrorists shot the military guys. "}],
    ["q6", "AcceptabilityJudgment", {s: "They always had a cure."}],
    ["q6", "AcceptabilityJudgment", {s: "They ate all our flowers."}],
    ["q6", "AcceptabilityJudgment", {s: "They endorsed themselves so they can get their picture out there."}],
    ["q6", "AcceptabilityJudgment", {s: "They increased the minimum wage."}],
    ["q6", "AcceptabilityJudgment", {s: "They just lived out their lives."}],
    ["q6", "AcceptabilityJudgment", {s: "They kept on top of that."}],
    ["q6", "AcceptabilityJudgment", {s: "They raised the rates of the thing."}],
    ["q6", "AcceptabilityJudgment", {s: "They repeated the same stuff."}],
    ["q6", "AcceptabilityJudgment", {s: "They sat in the cage."}],
    ["q6", "AcceptabilityJudgment", {s: "They saw who can eat the yuckiest stuff."}],
    ["q6", "AcceptabilityJudgment", {s: "They sent us our money."}],
    ["q6", "AcceptabilityJudgment", {s: "They should let 'em make money off of it."}],
    ["q6", "AcceptabilityJudgment", {s: "We cooperated with authorities."}],
    ["q6", "AcceptabilityJudgment", {s: "We looked at data."}],
    ["q6", "AcceptabilityJudgment", {s: "We sat down."}],
    ["q6", "AcceptabilityJudgment", {s: "We were alert."}],
    ["q6", "AcceptabilityJudgment", {s: "You found time."}],
    ["q6", "AcceptabilityJudgment", {s: "You incorporated."}],
    ["q6", "AcceptabilityJudgment", {s: "You just reached out."}],
    ["q6", "AcceptabilityJudgment", {s: "You just rode it out."}],
    ["q6", "AcceptabilityJudgment", {s: "You just started walking."}],
    ["q6", "AcceptabilityJudgment", {s: "You just stayed inside."}],
    ["q6", "AcceptabilityJudgment", {s: "You just voted."}],
    ["q6", "AcceptabilityJudgment", {s: "You knew how to catch fish."}],
    ["q6", "AcceptabilityJudgment", {s: "You lived your basic ways."}],
    ["q6", "AcceptabilityJudgment", {s: "You obviously worked out."}],
    ["q6", "AcceptabilityJudgment", {s: "You prayed for the safe return of all the other people."}],
    ["q6", "AcceptabilityJudgment", {s: "You shook the envelope."}],
    ["q6", "AcceptabilityJudgment", {s: "You signed up for like a million companies."}],
    ["q6", "AcceptabilityJudgment", {s: "You signed up for their messenger thing."}],
    ["q6", "AcceptabilityJudgment", {s: "You stepped out your door."}],
    ["q6", "AcceptabilityJudgment", {s: "You waited just a little while."}],
    ["q6", "AcceptabilityJudgment", {s: "You went."}],
    ["q6", "AcceptabilityJudgment", {s: "You were able to provide a quality service."}],
    ["q7", "AcceptabilityJudgment", {s: "He retrained all the policemen over there."}],
    ["q7", "AcceptabilityJudgment", {s: "Humans modified their environment."}],
    ["q7", "AcceptabilityJudgment", {s: "I changed the channel."}],
    ["q7", "AcceptabilityJudgment", {s: "I eliminated snails."}],
    ["q7", "AcceptabilityJudgment", {s: "I found some place that's got air conditioning."}],
    ["q7", "AcceptabilityJudgment", {s: "I heard what he has to say."}],
    ["q7", "AcceptabilityJudgment", {s: "I lived where I'm living."}],
    ["q7", "AcceptabilityJudgment", {s: "I owned a bookstore."}],
    ["q7", "AcceptabilityJudgment", {s: "I placed the call myself."}],
    ["q7", "AcceptabilityJudgment", {s: "I played the game off of TV."}],
    ["q7", "AcceptabilityJudgment", {s: "I signed up for this."}],
    ["q7", "AcceptabilityJudgment", {s: "I studied up."}],
    ["q7", "AcceptabilityJudgment", {s: "I took a computer class."}],
    ["q7", "AcceptabilityJudgment", {s: "I traveled."}],
    ["q7", "AcceptabilityJudgment", {s: "I turned it on."}],
    ["q7", "AcceptabilityJudgment", {s: "I washed my hands before I ate."}],
    ["q7", "AcceptabilityJudgment", {s: "I watch it step-by-step."}],
    ["q7", "AcceptabilityJudgment", {s: "It boosted their bottom line."}],
    ["q7", "AcceptabilityJudgment", {s: "It just increased your heart rate."}],
    ["q7", "AcceptabilityJudgment", {s: "Saddam released the chemical biological weapons."}],
    ["q7", "AcceptabilityJudgment", {s: "That created retaliation against Americans."}],
    ["q7", "AcceptabilityJudgment", {s: "They connected the D.C. area to New York."}],
    ["q7", "AcceptabilityJudgment", {s: "They did the voucher system."}],
    ["q7", "AcceptabilityJudgment", {s: "They informed the public."}],
    ["q7", "AcceptabilityJudgment", {s: "They just pulled that much more money out of you."}],
    ["q7", "AcceptabilityJudgment", {s: "They played golf."}],
    ["q7", "AcceptabilityJudgment", {s: "They remembered."}],
    ["q7", "AcceptabilityJudgment", {s: "They saw how."}],
    ["q7", "AcceptabilityJudgment", {s: "They took your name."}],
    ["q7", "AcceptabilityJudgment", {s: "They wore less and less clothing in each video."}],
    ["q7", "AcceptabilityJudgment", {s: "We drained it."}],
    ["q7", "AcceptabilityJudgment", {s: "We provided."}],
    ["q7", "AcceptabilityJudgment", {s: "We told people who show up with pets where their pet-friendly shelter is."}],
    ["q7", "AcceptabilityJudgment", {s: "We told them how to do it."}],
    ["q7", "AcceptabilityJudgment", {s: "We traveled back in time."}],
    ["q7", "AcceptabilityJudgment", {s: "We understood more about exactly what bioterrorism is."}],
    ["q7", "AcceptabilityJudgment", {s: "We were aware of people that just don't fit."}],
    ["q7", "AcceptabilityJudgment", {s: "You created an environment where they're forced to do something."}],
    ["q7", "AcceptabilityJudgment", {s: "You got on base."}],
    ["q7", "AcceptabilityJudgment", {s: "You increased the number of terrorists."}],
    ["q7", "AcceptabilityJudgment", {s: "You just reduced the amount of cigarettes you smoke every week."}],
    ["q7", "AcceptabilityJudgment", {s: "You knew somebody in the industry."}],
    ["q7", "AcceptabilityJudgment", {s: "You made enough difference so somebody else notices what you do."}],
    ["q7", "AcceptabilityJudgment", {s: "You released some of these germs or viruses."}],
    ["q7", "AcceptabilityJudgment", {s: "You said it was an accident."}],
    ["q7", "AcceptabilityJudgment", {s: "You stayed away from crowds."}],
    ["q7", "AcceptabilityJudgment", {s: "You tried."}],
    ["q7", "AcceptabilityJudgment", {s: "You used that as an engine rather than an impediment."}],
    ["q7", "AcceptabilityJudgment", {s: "You watched the nighttime news."}],
    ["q7", "AcceptabilityJudgment", {s: "You were more prepared for it."}],
    ["q7", "AcceptabilityJudgment", {s: "Your husband just hung out around the major hotels."}]

];
